---
server:
  port: 8085

spring:
  output:
    ansi:
      enabled: detect
  http:
    converters:
      preferred-json-mapper: jackson
  jackson:
    default-property-inclusion: non_null
    time-zone: UTC
  security:
    user:
      name: dev
      password: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/serviceregistry
    username: serviceregistry
    password: serviceregistry
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: false
      leak-detection-threshold: 2000

management:
  endpoints:
    web:
      exposure:
        include: "health"
  server:
    add-application-context-header: false

app:
  service-info:
    id: "org.ga4gh.service-registry"
    name: "GA4GH Service Registry Reference Implementation"
    type: "org.ga4gh:service-registry:1.0.0"
    description: "Reference implementation of GA4GH Service Registry"
    organization:
      name: "GA4GH"
      url: "https://example.com"
    contact-url: "mailto:support@example.com"
    documentation-url: "https://github.com/ga4gh-discovery/ga4gh-service-registry"
    environment: "dev"
    version: 1.0.0

logging:
  level:
    org.jdbi: INFO
    com.dnastack.discovery.registry: DEBUG